[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "celery -A services.celery_worker worker --loglevel=info"
restartPolicy = "on-failure"
maxRestarts = 10

[env]
PORT = "5000"
FLASK_ENV = "production"

[[services]]
internalPort = 5000
protocol = "http"
[services.concurrency]
type = "connections"
hard = 100
soft = 80

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[statics]]
guest = "/app/static"
url = "/static"

[[plugins]]
type = "redis"